---
- hosts: all
  connection: local
  become: yes

  vars:
    current_user: "{{ ansible_user_id }}"

  vars_files:
    - config.yml

  tasks:
    - name: Running playbook as user
      debug:
        msg: "Running as user: {{ current_user }}"

    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
      tags: ['homebrew', 'ci']

    - name: Setup Homebrew taps
      homebrew_tap:
        name: "{{ item }}"
        state: present
      tags: ['homebrew']
      loop: "{{ homebrew_taps }}"

    - name: Install Homebrew packages
      homebrew:
        name: "{{ item.name | default(item) }}"
        install_options: "{{ item.install_options | default(omit) }}"
        state: present
      loop: "{{ homebrew_installed_packages }}"
      tags: ['homebrew']
      register: result
      failed_when:
        - result.failed
        - item.allow_failure | default(false)

    - name: Install Homebrew cask packages
      homebrew_cask:
        name: "{{ item.name | default(item) }}"
        state: present
        install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
      loop: "{{ homebrew_cask_apps }}"
      tags: ['homebrew']
      register: result
      when: item.ci | default(True) | bool
      failed_when:
        - result.failed
        - item.allow_failure | default(false)

    - name: Install Macos App Store packages
      tags: ['mas', 'ci']
      include_role:
        name:  geerlingguy.mas

    - name: Fetch dns-heaven install script
      tags: ['dns-heaven']
      register: dns_heaven_install_script
      uri:
        url: https://git.io/fix-my-dns-plz
        return_content: yes

    - name: Install dns-heaven
      tags: ['dns-heaven']
      become: yes
      become_user: root
      shell: "{{ dns_heaven_install_script.content }}"

    - name: Read SETUP_DOTFILES_DIR
      tags: ['files']
      set_fact:
        dotfiles_dir: "{{ lookup('env', 'SETUP_DOTFILES_DIR') }}"

    - name: Make sure the variable is set
      tags: ['files']
      fail:
        msg: SETUP_DOTFILES_DIR is not set
      when: not dotfiles_dir

    - name: Ensure rcm is installed
      tags: ['files']
      homebrew:
        name: rcm
        state: present

    - name: Symlink all dotfiles
      tags: ['files']
      command: rcup -v
      register: rcm
      environment:
        RCRC: "{{ dotfiles_dir }}/files/rcrc"

    - name: Print rcm
      tags: ['files']
      debug:
        msg: "{{ rcm.stdout_lines }}"

    - name: Apply macos customisations
      tags: ['macos']
      command: "{{playbook_dir}}/macos_customisations.sh"

    - name: Get GitHub authorized key
      tags: ['git']
      command: ssh-keyscan -t rsa github.com
      register: github_key

    - name: Add GitHub authorized key to known hosts
      tags: ['git']
      known_hosts:
        hash_host: false
        name: github.com
        key: "{{ github_key.stdout }}"
        path: "{{ lookup('env','HOME') }}/.ssh/known_hosts"
        state: present

    - name: Ensure mr is installed
      tags: ['git']
      homebrew:
        name: mr
        state: present

    - name: Clone all repositories
      tags: ['git']
      command: mr checkout -j 8
      args:
        chdir: "{{ lookup('env','HOME') }}"

    - name: Ensure zsh is installed
      tags: ['shell']
      homebrew:
        name: zsh
        state: present

    - name: Set the ZSH version from brew
      tags: ['shell']
      become: yes
      become_user: root
      user:
        name: "{{ current_user }}"
        shell: /usr/local/bin/zsh

    - name: Ensure proper permissions for ZSH
      tags: ['shell']
      become: yes
      become_user: root
      file:
        path: /usr/local/share/zsh
        recurse: yes
        mode: '0755'

    - name : Generate updated PATH
      shell: "source {{ lookup('env','HOME') }}/.zshrc; echo $PATH"
      tags: ['shell', 'lang']
      args:
         executable: /usr/local/bin/zsh
      register: updated_path

    - name: Install ASDF plugins
      command: "asdf plugin add {{ item.key }}"
      loop: "{{ languages | dict2items }}"
      tags: ['lang']
      register: result
      failed_when:
        - result.rc != 0
        - '"already added" not in result.stderr'

    - name: Update ASDF plugins
      command: "asdf plugin update {{ item.key }}"
      loop: "{{ languages | dict2items }}"
      tags: ['lang']

    - name: Install ASDF language versions
      include_tasks: asdf_install.yml
      tags: ['lang']
      loop: "{{ languages | dict2items | map(attribute='key') | list }}"
      loop_control:
        loop_var: language

    - name: Set ASDF global versions
      command: "asdf global {{ item }} {{ languages[item].global }}"
      tags: ['lang']
      loop: "{{ languages | dict2items | map(attribute='key') | list }}"

    - name: Install Nodejs packages for all versions
      tags: ['lang']
      environment:
        ASDF_NODEJS_VERSION: '{{ item[1] }}'
        PATH: '{{ updated_path }}'
      npm:
        name: "{{ item[0].name }}"
        state: "{{ 'present' if (item[0].version | default(None)) else 'latest' }}"
        global: yes
      with_nested:
        - "{{ languages.nodejs.packages }}"
        - "{{ languages.nodejs.versions | map(attribute='version') | list }}"

    - name: Install Nodejs packages specific for version
      tags: ['lang']
      environment:
        ASDF_NODEJS_VERSION: '{{ item[0].version }}'
        PATH: '{{ updated_path }}'
      npm:
        name: "{{ item[1].name }}"
        state: "{{ 'present' if (item[1].version | default(None)) else 'latest' }}"
        global: yes
      with_subelements:
        - "{{ languages.nodejs.versions }}"
        - packages

    - name: Install Ruby gems for all versions
      tags: ['lang']
      environment:
        ASDF_RUBY_VERSION: '{{ item[1] }}'
        PATH: '{{ updated_path }}'
      gem:
        name: "{{ item[0].name }}"
        state: "{{ 'present' if (item[0].version | default(None)) else 'latest' }}"
        build_flags: "{{ item[0].build_flags | default(None) }}"
        user_install: false
      with_nested:
        - "{{ languages.ruby.gems }}"
        - "{{ languages.ruby.versions | map(attribute='version') | list }}"

    - name: Install Ruby gems specific for version
      tags: ['lang']
      environment:
        ASDF_RUBY_VERSION: '{{ item[0].version }}'
        PATH: '{{ updated_path }}'
      gem:
        name: "{{ item[1].name }}"
        state: "{{ 'present' if (item[1].version | default(None)) else 'latest' }}"
        build_flags: "{{ item[1].build_flags | default(None) }}"
        user_install: false
      with_subelements:
        - "{{ languages.ruby.versions }}"
        - gems

    - name: Install solargraph documentation
      tags: ['lang']
      environment:
        ASDF_RUBY_VERSION: '{{ item.version }}'
        PATH: '{{ updated_path }}'
      command: solargraph download-core {{ item.solargraph }}
      changed_when: False
      loop: "{{ languages.ruby.versions }}"

    - name: Generate YARD documentation for all Ruby versions
      tags: ['lang']
      environment:
        ASDF_RUBY_VERSION: '{{ item }}'
        PATH: '{{ updated_path }}'
      command: yard gems
      changed_when: False
      loop: "{{ languages.ruby.versions | map(attribute='version') | list }}"

    - name: Reshim asdf
      tags: ['lang']
      command: asdf reshim
      changed_when: False

    # - name: "Sync secrets stored in 1password"
    #   tags: ['secrets']
    #   command: op_sync sync
    #   register: op_sync
    #   changed_when: (op_sync.stdout | from_json)['total_updates'] > 0

    # - name: "Restart gpg-agent"
    #   tags: ['secrets']
    #   command: gpgconf --reload gpg-agent
