apiVersion: v1
kind: Service
metadata:
  name: resilio
  labels:
    app: resilio
    kubernetes.io/name: "resilio"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.10
  selector:
    app: resilio
  ports:
  - name: resilio-ui
    port: 80
    targetPort: 8888
    protocol: TCP
  - name: resilio-sync
    port: 55555
    targetPort: 55555
    protocol: TCP
