apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
    kubernetes.io/name: "radarr"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.13
  selector:
    app: radarr
  ports:
  - name: radarr-ui
    port: 80
    targetPort: 7878
    protocol: TCP
