service_cidr: "10.96.0.0/12"
pod_network_cidr: "10.244.0.0/16"

master_host: "{{ hostvars[groups['master_group'][0]] }}"

flannel_manifest: "https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml"
