package:
  kubeadm:
    installed: true
    versions:
    - 1.17.0-00
  kubectl:
    installed: true
    versions:
    - 1.17.0-00
  kubelet:
    installed: true
    versions:
    - 1.17.0-00
service:
  docker:
    enabled: true
    running: true
  kubelet:
    enabled: true
    running: true
user:
  debian:
    exists: true
    uid: 1000
    gid: 1000
    groups:
    - debian
    home: /home/debian
    shell: /bin/bash
group:
  docker:
    exists: true
    gid: 999
command:
  df -h /dev/sda1 --output=size:
    title: Make sure the root disk has grown to 31 gigabytes
    exit-status: 0
    stdout:
    - Size
    - 31G
    stderr: []
    timeout: 10000
  docker.cgroup:
    title: Make sure docker uses systemd as cgroup driver
    meta:
      desc: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers
    exec: docker info --format '{{"{{json .CgroupDriver}}"}}'
    exit-status: 0
    stdout:
    - '"systemd"'
    stderr: []
    timeout: 10000
dns:
  dns.msftncsi.com:
    title: Test if DNS resolution is working
    meta:
      desc: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ee126135(v=ws.10)?redirectedfrom=MSDN#how-ncsi-communicates-with-an-internet-site
    resolvable: true
    addrs:
    - 131.107.255.255
    - fd3e:4f5a:5b81::1
    timeout: 500
  localhost:
    resolvable: true
    addrs:
    - 127.0.0.1
    timeout: 500
mount:
  /:
    title: Make sure there is enough disk space available
    exists: true
    opts:
    - rw
    - relatime
    source: /dev/sda1
    filesystem: ext4
    usage:
      lt: 90
