package:
  kubeadm:
    installed: true
    versions:
    - 1.17.3-00
  kubectl:
    installed: true
    versions:
    - 1.17.3-00
  kubelet:
    installed: true
    versions:
    - 1.17.3-00
service:
  docker:
    enabled: true
    running: true
user:
  kube:
    exists: true
    uid: 1001
    gid: 1001
    groups:
    - kube
    - docker
    home: /home/kube
    shell: /bin/bash
group:
  docker:
    exists: true
    gid: 999
matching:
  check_disk_usage:
    title: Check if the root disk "/" has a total capacity >= 25 GiB
    content: {{ (index .Vars.mountpoints "/").size_bytes }}
    matches:
      ge: 26843545600
command:
  docker.cgroup:
    title: Make sure docker uses systemd as cgroup driver
    meta:
      desc: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers
    exec: docker info --format '{{"{{json .CgroupDriver}}"}}'
    exit-status: 0
    stdout:
    - '"systemd"'
    stderr: []
    timeout: 10000
dns:
  dns.msftncsi.com:
    title: Test if DNS resolution is working
    meta:
      desc: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ee126135(v=ws.10)?redirectedfrom=MSDN#how-ncsi-communicates-with-an-internet-site
    resolvable: true
    addrs:
    - 131.107.255.255
    - fd3e:4f5a:5b81::1
    timeout: 500
  localhost:
    resolvable: true
    addrs:
    - 127.0.0.1
    timeout: 500
mount:
  /:
    title: Make sure there is enough disk space available
    exists: true
    opts:
    - rw
    - relatime
    source: {{ (index .Vars.mountpoints "/").device }}
    filesystem: ext4
    usage:
      lt: 90
