---
- hosts: master
  gather_facts: no
  become_method: sudo
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:

    - name: Gathering facts
      setup:

    - name: Reset Kubernetes cluster
      become: yes
      command: |
        kubeadm reset --force

    - name: Init Kubernetes cluster
      become: yes
      command: |
        kubeadm init --service-cidr {{ service_cidr }}
                     --pod-network-cidr {{ pod_network_cidr }}
                     --apiserver-advertise-address {{ master_ip }}

    - name: Generate Kubernetes join token
      become: yes
      register: join_command
      command: |
        kubeadm token create --print-join-command

    - name: Create kubectl config directory
      file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"

    - name: Copy kubectl config
      become: yes
      copy:
        remote_src: true
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_user_dir }}/.kube/config"
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"

    - name: Initialize flannel network
      command: |
        kubectl apply -f {{ flannel_manifest }}


    - name: LE DEBUG
      tags: ['test']
      debug:
        msg: "{{ inventory_hostname }} - {{ inventory_hostname_short }}"

    - name: Wait for master to be ready
      tags: ['test']
      environment:
        # https://kubernetes.io/docs/reference/kubectl/cheatsheet/#viewing-finding-resources
        JSONPATH: '{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}'
      command: "kubectl get node {{ inventory_hostname_short }} -o jsonpath=$JSONPATH"
      register: master_status
      until:
        - '"Ready=True" in master_status.stdout'
      retries: 60
      delay: 2

- hosts: worker
  gather_facts: no
  become_method: sudo
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:

    - name: Gathering facts
      setup:

    - name: Reset Kubernetes cluster
      become: yes
      command: |
        kubeadm reset --force

    - set_fact:
        join_command: "{{ master_host['join_command']['stdout'] }}"

    - name: Join Kubernetes cluster
      become: yes
      command: |
        {{ join_command }}
