#cloud-config

hostname: razor-server
manage_etc_hosts: localhost

users:
  - name: vagrant
    plain_text_passwd: vagrant
    lock_passwd: false
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6z3EzufNOqkC9M4cAhzusOPb+mX5IXDCCBVuWg8wnjbgneKQLehVtG3Yp1XB+baU2HzNr6o3+ulumx4fo5fuPiYoOIpplazaSx7b3zmTeYLCx0mdViZjftv/7lKui+XMwmDC/AhdDEBiG3f6HTifow0SQ3Df9xNFzkrgTm61v9QXVKZUgmSJvOUxIr/kvYSPzgWFjl9EztM60myPhpfjW3jlRwyjtBJYYFyHnXGA6qDflS4PALpAVotTzVTMhXSs0vJe+chgLXGPVMsL+CwRJjtE/pZ0cBQOLXuDV82AaS3GRrexFVe0G+9ap8fglc/DVP1c6u9+LBXcafLO7A5TN4Fu/CRDvzcDMXXxUOOSDmkdtynpnK4Ah2S65q8SUz67VDovU6XSpQc2Ys41uGFllLleSpsIaQOZcXrqg8RsQZ2PXRid+UYIl6j/iAsE2XYuomJYPS2Am1moEA8Orbw64y+ZJ3iMEQGPpkMdJlTiASWorYSwareV4Vaof7YWCob8= public-key

write_files:
- content: |
    # Configuration file for /sbin/dhclient.
    #
    # This is a sample configuration file for dhclient. See dhclient.conf's
    #	man page for more information about the syntax of this file
    #	and a more comprehensive list of the parameters understood by
    #	dhclient.
    #
    # Normally, if the DHCP server provides reasonable information and does
    #	not leave anything out (like the domain name, for example), then
    #	few changes must be made to this file, if any.
    #

    option rfc3442-classless-static-routes code 121 = array of unsigned integer 8;

    send host-name = gethostname();
    request subnet-mask, broadcast-address, time-offset, routers,
      domain-name, domain-name-servers, domain-search, host-name,
      dhcp6.name-servers, dhcp6.domain-search, dhcp6.fqdn, dhcp6.sntp-servers,
      netbios-name-servers, netbios-scope, interface-mtu,
      rfc3442-classless-static-routes, ntp-servers;

    interface "enp0s8" {
      # Empty request removes all previous entries
      request;

      # Do not request the dns / nameservers from the LAN interface
      request subnet-mask, broadcast-address, time-offset, routers,
        host-name,
        dhcp6.fqdn, dhcp6.sntp-servers,
        netbios-name-servers, netbios-scope, interface-mtu,
        rfc3442-classless-static-routes, ntp-servers;

      supersede domain-name-servers 192.168.3.1;
    }

  path: /etc/dhcp/dhclient.conf

# Restart networking only during first boot to fix the wrong hostname in dhcp server
runcmd:
  - [systemctl, restart, networking]
