name: Test
on: [push]

jobs:
  image_builder:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # - name: Test action
    #   if: always()
    #   uses: ./.github/actions/create_disk_image.yml

    - name: Build
      if: always()
      run: |
        docker build
        --tag image-builder:bionic
        -f kubernetes/Dockerfile
        kubernetes

    - name: Run
      if: always()
      run: |
        docker run --rm -it --privileged -v $PWD/kubernetes/images:/app -v $PWD/kubernetes/elements:/elements image-builder:bionic

    # - name: Test kvm
    #   if: always()
    #   run: kvm-ok

    # - name: Test CPU info
    #   if: always()
    #   run: egrep -c '(vmx|svm)' /proc/cpuinfo

    # - name: Test CPU info
    #   if: always()
    #   run: cat /sys/hypervisor/properties/capabilities

  test1:
    name: Test 1
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Test action
      if: always()
      uses: ./

    - name: Test qemu
      if: always()
      run: |
        qemu-img --help

    - name: Test brew
      if: always()
      run: |
        brew info

    - name: Test docker
      if: always()
      run: |
        docker info

    - uses: actions/checkout@v1
      with:
        ref: ${{ matrix.ref }}
