name: Test
on: [push]

jobs:
  test1:
    name: Test 1
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Test action
      if: always()
      uses: ./

    - name: Test qemu
      if: always()
      run: |
        qemu-img --help

    - name: Test brew
      if: always()
      run: |
        brew info

    - name: Test docker
      if: always()
      run: |
        docker info

    - uses: actions/checkout@v1
      with:
        ref: ${{ matrix.ref }}
