name: Test
on: [push]

jobs:
  test-dotfiles:
    name: Test dotfiles
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      # First uninstall homebrew? https://github.com/homebrew/install#uninstall-homebrew
      # For debugging https://github.com/marketplace/actions/debugging-with-tmate
    - uses: actions/checkout@v1
    - run: ./scripts/github_load_env.sh
    - run: env
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - run: |
        export CI_PASSWORD=""
        export BRANCH="$GIT_BRANCH"
        eval "$(cat ./dotfiles/bootstrap.sh)" < <(echo $CI_PASSWORD)
    - working-directory: ${{ env.SETUP_DOTFILES_DIR }}
      run: bundle install
    - working-directory: ${{ env.SETUP_DOTFILES_DIR }}
      run: rake spec
