name: Test
on: [push]
env:
  CI: true
  REGISTRY_GITHUB_TOKEN: ${{ github.token }}

jobs:
  base-image:
    name: Build docker base image
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - env:
        GITHUB: ${{ toJson(github) }}
        ENV: ${{ toJson(env) }}
        JOB: ${{ toJson(job) }}
        STEPS: ${{ toJson(steps) }}
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        STRATEGY: ${{ toJson(strategy) }}
        MATRIX: ${{ toJson(matrix) }}
      run: |
        env
    - uses: actions/checkout@v1
    - run: ./scripts/load_env.sh
    - run: docker_build.sh "${BASE_IMAGE}" "./base-image"

  image-builder:
    name: Build image builder image
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: base-image
    steps:
    - uses: actions/checkout@v1
    - run: ./scripts/load_env.sh
    - run: docker_build.sh "${IMAGE_BUILDER_IMAGE}" "./image-builder"

  razor-server:
    name: Build razor server image
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: base-image
    steps:
    - uses: actions/checkout@v1
    - run: ./scripts/load_env.sh
    - run: docker_build.sh "${RAZOR_SERVER_IMAGE}" "./razor-server"

  build-deploy-image:
    name: Build deploy image
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: image-builder
    steps:
    - uses: actions/checkout@v1
    - run: ./scripts/load_env.sh
    - run: ./deploy-image/build-image.sh
    - uses: actions/upload-artifact@v1
      with:
        name: deploy-image
        path: ./deploy-image/images/deploy-image

  test-deploy-image:
    name: Test deploy image
    timeout-minutes: 10
    runs-on: macos-latest
    needs: build-deploy-image
    steps:
    - uses: actions/checkout@v1
    - run: ./scripts/load_env.sh
    - run: brew install qemu cdrtools hivemind hyperkit
    - uses: actions/download-artifact@v1
      with:
        name: deploy-image
        path: ./deploy-image/images/deploy-image
    - run: |
        cd ./deploy-image;
        hivemind Procfile.tests

  build-kubernetes:
    name: Build kubernetes image
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: image-builder
    steps:
    - uses: actions/checkout@v1
    - run: ./scripts/load_env.sh
    - run: ./kubernetes/build-image.sh
    - uses: actions/upload-artifact@v1
      with:
        name: kubernetes
        path: ./kubernetes/images/kubernetes

  test-kubernetes:
    name: Test kubernetes image
    timeout-minutes: 10
    runs-on: macos-latest
    needs: build-kubernetes
    steps:
    - uses: actions/checkout@v1
    - run: ./scripts/load_env.sh
    - run: brew install qemu cdrtools hivemind hyperkit ansible
    - uses: actions/download-artifact@v1
      with:
        name: kubernetes
        path: ./kubernetes/images/kubernetes
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: gem install bundler:2.1.4
    - run: cd kubernetes && bundle install
    - run: chmod 0400 scripts/keys/id_rsa
    - run: |
        cd ./kubernetes;
        hivemind Procfile.tests &
        bundle exec rspec
